services:
  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}"
    ports:
      - "${PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./home/bin:/app
