name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Publish with dotnet
      run: dotnet publish --configuration Release Home/Home.csproj

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Home
        path: Home/bin/Release/net8.0/publish
